  <!-- MENU START -->
  <td style="vertical-align: top;" rowspan="1" colspan="1">
    <table border="0" cellpadding="0" cellspacing="0">
      <tr valign="top">
        <td width="150" bgcolor="#f0f0f0">
          <table width="100%" cellpadding="2" cellspacing="0" border="0">
            <tr valign="top">
              <td class="sidebar">
                <p><a href="/index.php">HOME</a></p>                
                <p><a href="/ini_desc.php">INI file description</a></p>                
                <!-- hr noshade="noshade" size="1" color="#000000" / -->
                <hr noshade="noshade" size="1" />
                <p><a href="http://developer.berlios.de/projects/sftp4tc/">
                     <img src="http://developer.berlios.de/bslogo.php?group_id=0&amp;type=1" width="124" height="32" border="0" alt="BerliOS Logo">
                   </a>
               </p>
               <p><a href="http://developer.berlios.de/projects/sftp4tc/">Summary</a></p>
               <p><a href="http://developer.berlios.de/docman/?group_id=2273">FAQ</a></p>
               <p><a href="http://developer.berlios.de/news/?group_id=2273">News</a></p>
               <p><a href="http://developer.berlios.de/forum/?group_id=2273">Forums</a></p>
               <p><a href="http://developer.berlios.de/bugs/?group_id=2273">Bugs</a></p>
               <p><a href="http://developer.berlios.de/feature/?group_id=2273">Features</a></p>
               <p><a href="http://developer.berlios.de/project/filelist.php?group_id=2273">Files</a></p>
               <p>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="9490307">
<input type="image" src="https://www.paypal.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="Donate for SFTP4TC!">
<img alt="" border="0" src="https://www.paypal.com/de_DE/i/scr/pixel.gif" width="1" height="1">
</form>
               </p><p>
                 <a href="http://validator.w3.org/check?uri=referer">
                  <img border="0"
                       src="http://www.w3.org/Icons/valid-html401"
                       alt="Valid HTML 4.01!" height="31" width="88"></a>
               </p>
              </td>
            </tr>
         </table>
        </td>
      </tr>
   </table>
  </td>
  <!-- MENU END -->  
